bootstrap.servers = <BOOTSTRAP_SERVER:PORT> 
sasl.jaas.config = org.apache.kafka.common.security.plain.PlainLoginModule required username='<PLAIN USER>' password='<PASSWORD>';
# Options are PLAIN, SCRAM-SHA-512, GSSAPI, OAUTHBEARER
sasl.mechanism=PLAIN
# Options are SSL, PLAINTEXT, SASL_SSL, SASL_PLAINTEXT
security.protocol=SASL_SSL
#--------------------------------
## To be filled in if TLS is enabled for the Brokers
# Options are PKCS12, JKS, PEM. Password not required for PEM.
ssl.truststore.type=JKS
ssl.truststore.location=<LOCATION OF TRUSTSTORE>
ssl.truststore.password=<TRUSTSTORE PASSWORD>
#--------------------------------
